package imguijs;

import imguijs.Abstracts;

/**
	Generated by `tools/generate-jsimgui-externs.mjs` from
	`runtime/jsimgui/*.d.ts`.
**/

typedef ImPlotContext = Float;
typedef ImPlotInputMap = Float;
typedef ImPlotStyle = Float;

abstract ImAxis(Int) from Int to Int {
	public static inline final X1:ImAxis = 0;
	public static inline final X2:ImAxis = 1;
	public static inline final X3:ImAxis = 2;
	public static inline final Y1:ImAxis = 3;
	public static inline final Y2:ImAxis = 4;
	public static inline final Y3:ImAxis = 5;
	public static inline final COUNT:ImAxis = 6;
}

abstract ImPlotAxisFlags(Int) from Int to Int {
	public static inline final None:ImPlotAxisFlags = 0;
	public static inline final NoLabel:ImPlotAxisFlags = 1;
	public static inline final NoGridLines:ImPlotAxisFlags = 2;
	public static inline final NoTickMarks:ImPlotAxisFlags = 4;
	public static inline final NoTickLabels:ImPlotAxisFlags = 8;
	public static inline final NoInitialFit:ImPlotAxisFlags = 16;
	public static inline final NoMenus:ImPlotAxisFlags = 32;
	public static inline final NoSideSwitch:ImPlotAxisFlags = 64;
	public static inline final NoHighlight:ImPlotAxisFlags = 128;
	public static inline final Opposite:ImPlotAxisFlags = 256;
	public static inline final Foreground:ImPlotAxisFlags = 512;
	public static inline final Invert:ImPlotAxisFlags = 1024;
	public static inline final AutoFit:ImPlotAxisFlags = 2048;
	public static inline final RangeFit:ImPlotAxisFlags = 4096;
	public static inline final PanStretch:ImPlotAxisFlags = 8192;
	public static inline final LockMin:ImPlotAxisFlags = 16384;
	public static inline final LockMax:ImPlotAxisFlags = 32768;
	public static inline final Lock:ImPlotAxisFlags = 49152;
	public static inline final NoDecorations:ImPlotAxisFlags = 15;
	public static inline final AuxDefault:ImPlotAxisFlags = 258;
}

abstract ImPlotBarGroupsFlags(Int) from Int to Int {
	public static inline final None:ImPlotBarGroupsFlags = 0;
	public static inline final Horizontal:ImPlotBarGroupsFlags = 1024;
	public static inline final Stacked:ImPlotBarGroupsFlags = 2048;
}

abstract ImPlotBarsFlags(Int) from Int to Int {
	public static inline final None:ImPlotBarsFlags = 0;
	public static inline final Horizontal:ImPlotBarsFlags = 1024;
}

abstract ImPlotBin(Int) from Int to Int {
	public static inline final Sqrt:ImPlotBin = -1;
	public static inline final Sturges:ImPlotBin = -2;
	public static inline final Rice:ImPlotBin = -3;
	public static inline final Scott:ImPlotBin = -4;
}

abstract ImPlotBubblesFlags(Int) from Int to Int {
	public static inline final None:ImPlotBubblesFlags = 0;
}

abstract ImPlotCol(Int) from Int to Int {
	public static inline final FrameBg:ImPlotCol = 0;
	public static inline final PlotBg:ImPlotCol = 1;
	public static inline final PlotBorder:ImPlotCol = 2;
	public static inline final LegendBg:ImPlotCol = 3;
	public static inline final LegendBorder:ImPlotCol = 4;
	public static inline final LegendText:ImPlotCol = 5;
	public static inline final TitleText:ImPlotCol = 6;
	public static inline final InlayText:ImPlotCol = 7;
	public static inline final AxisText:ImPlotCol = 8;
	public static inline final AxisGrid:ImPlotCol = 9;
	public static inline final AxisTick:ImPlotCol = 10;
	public static inline final AxisBg:ImPlotCol = 11;
	public static inline final AxisBgHovered:ImPlotCol = 12;
	public static inline final AxisBgActive:ImPlotCol = 13;
	public static inline final Selection:ImPlotCol = 14;
	public static inline final Crosshairs:ImPlotCol = 15;
	public static inline final COUNT:ImPlotCol = 16;
}

abstract ImPlotColormapScaleFlags(Int) from Int to Int {
	public static inline final None:ImPlotColormapScaleFlags = 0;
	public static inline final NoLabel:ImPlotColormapScaleFlags = 1;
	public static inline final Opposite:ImPlotColormapScaleFlags = 2;
	public static inline final Invert:ImPlotColormapScaleFlags = 4;
}

abstract ImPlotColormap(Int) from Int to Int {
	public static inline final Deep:ImPlotColormap = 0;
	public static inline final Dark:ImPlotColormap = 1;
	public static inline final Pastel:ImPlotColormap = 2;
	public static inline final Paired:ImPlotColormap = 3;
	public static inline final Viridis:ImPlotColormap = 4;
	public static inline final Plasma:ImPlotColormap = 5;
	public static inline final Hot:ImPlotColormap = 6;
	public static inline final Cool:ImPlotColormap = 7;
	public static inline final Pink:ImPlotColormap = 8;
	public static inline final Jet:ImPlotColormap = 9;
	public static inline final Twilight:ImPlotColormap = 10;
	public static inline final RdBu:ImPlotColormap = 11;
	public static inline final BrBG:ImPlotColormap = 12;
	public static inline final PiYG:ImPlotColormap = 13;
	public static inline final Spectral:ImPlotColormap = 14;
	public static inline final Greys:ImPlotColormap = 15;
}

abstract ImPlotCond(Int) from Int to Int {
	public static inline final None:ImPlotCond = 0;
	public static inline final Always:ImPlotCond = 1;
	public static inline final Once:ImPlotCond = 2;
}

abstract ImPlotDateFmt(Int) from Int to Int {
	public static inline final None:ImPlotDateFmt = 0;
	public static inline final DayMo:ImPlotDateFmt = 1;
	public static inline final DayMoYr:ImPlotDateFmt = 2;
	public static inline final MoYr:ImPlotDateFmt = 3;
	public static inline final Mo:ImPlotDateFmt = 4;
	public static inline final Yr:ImPlotDateFmt = 5;
}

abstract ImPlotDigitalFlags(Int) from Int to Int {
	public static inline final None:ImPlotDigitalFlags = 0;
}

abstract ImPlotDragToolFlags(Int) from Int to Int {
	public static inline final None:ImPlotDragToolFlags = 0;
	public static inline final NoCursors:ImPlotDragToolFlags = 1;
	public static inline final NoFit:ImPlotDragToolFlags = 2;
	public static inline final NoInputs:ImPlotDragToolFlags = 4;
	public static inline final Delayed:ImPlotDragToolFlags = 8;
}

abstract ImPlotDummyFlags(Int) from Int to Int {
	public static inline final None:ImPlotDummyFlags = 0;
}

abstract ImPlotErrorBarsFlags(Int) from Int to Int {
	public static inline final None:ImPlotErrorBarsFlags = 0;
	public static inline final Horizontal:ImPlotErrorBarsFlags = 1024;
}

abstract ImPlotFlags(Int) from Int to Int {
	public static inline final None:ImPlotFlags = 0;
	public static inline final NoTitle:ImPlotFlags = 1;
	public static inline final NoLegend:ImPlotFlags = 2;
	public static inline final NoMouseText:ImPlotFlags = 4;
	public static inline final NoInputs:ImPlotFlags = 8;
	public static inline final NoMenus:ImPlotFlags = 16;
	public static inline final NoBoxSelect:ImPlotFlags = 32;
	public static inline final NoFrame:ImPlotFlags = 64;
	public static inline final Equal:ImPlotFlags = 128;
	public static inline final Crosshairs:ImPlotFlags = 256;
	public static inline final CanvasOnly:ImPlotFlags = 55;
}

abstract ImPlotHeatmapFlags(Int) from Int to Int {
	public static inline final None:ImPlotHeatmapFlags = 0;
	public static inline final ColMajor:ImPlotHeatmapFlags = 1024;
}

abstract ImPlotHistogramFlags(Int) from Int to Int {
	public static inline final None:ImPlotHistogramFlags = 0;
	public static inline final Horizontal:ImPlotHistogramFlags = 1024;
	public static inline final Cumulative:ImPlotHistogramFlags = 2048;
	public static inline final Density:ImPlotHistogramFlags = 4096;
	public static inline final NoOutliers:ImPlotHistogramFlags = 8192;
	public static inline final ColMajor:ImPlotHistogramFlags = 16384;
}

abstract ImPlotImageFlags(Int) from Int to Int {
	public static inline final None:ImPlotImageFlags = 0;
}

abstract ImPlotInfLinesFlags(Int) from Int to Int {
	public static inline final None:ImPlotInfLinesFlags = 0;
	public static inline final Horizontal:ImPlotInfLinesFlags = 1024;
}

abstract ImPlotItemFlags(Int) from Int to Int {
	public static inline final None:ImPlotItemFlags = 0;
	public static inline final NoLegend:ImPlotItemFlags = 1;
	public static inline final NoFit:ImPlotItemFlags = 2;
}

abstract ImPlotLegendFlags(Int) from Int to Int {
	public static inline final None:ImPlotLegendFlags = 0;
	public static inline final NoButtons:ImPlotLegendFlags = 1;
	public static inline final NoHighlightItem:ImPlotLegendFlags = 2;
	public static inline final NoHighlightAxis:ImPlotLegendFlags = 4;
	public static inline final NoMenus:ImPlotLegendFlags = 8;
	public static inline final Outside:ImPlotLegendFlags = 16;
	public static inline final Horizontal:ImPlotLegendFlags = 32;
	public static inline final Sort:ImPlotLegendFlags = 64;
	public static inline final Reverse:ImPlotLegendFlags = 128;
}

abstract ImPlotLineFlags(Int) from Int to Int {
	public static inline final None:ImPlotLineFlags = 0;
	public static inline final Segments:ImPlotLineFlags = 1024;
	public static inline final Loop:ImPlotLineFlags = 2048;
	public static inline final SkipNaN:ImPlotLineFlags = 4096;
	public static inline final NoClip:ImPlotLineFlags = 8192;
	public static inline final Shaded:ImPlotLineFlags = 16384;
}

abstract ImPlotLocation(Int) from Int to Int {
	public static inline final Center:ImPlotLocation = 0;
	public static inline final North:ImPlotLocation = 1;
	public static inline final South:ImPlotLocation = 2;
	public static inline final West:ImPlotLocation = 4;
	public static inline final East:ImPlotLocation = 8;
	public static inline final NorthWest:ImPlotLocation = 5;
	public static inline final NorthEast:ImPlotLocation = 9;
	public static inline final SouthWest:ImPlotLocation = 6;
	public static inline final SouthEast:ImPlotLocation = 10;
}

abstract ImPlotMarkerInternal(Int) from Int to Int {
	public static inline final Marker_Invalid:ImPlotMarkerInternal = -3;
}

abstract ImPlotMarker(Int) from Int to Int {
	public static inline final None:ImPlotMarker = -2;
	public static inline final Auto:ImPlotMarker = -1;
	public static inline final Circle:ImPlotMarker = 0;
	public static inline final Square:ImPlotMarker = 1;
	public static inline final Diamond:ImPlotMarker = 2;
	public static inline final Up:ImPlotMarker = 3;
	public static inline final Down:ImPlotMarker = 4;
	public static inline final Left:ImPlotMarker = 5;
	public static inline final Right:ImPlotMarker = 6;
	public static inline final Cross:ImPlotMarker = 7;
	public static inline final Plus:ImPlotMarker = 8;
	public static inline final Asterisk:ImPlotMarker = 9;
	public static inline final COUNT:ImPlotMarker = 10;
}

abstract ImPlotMouseTextFlags(Int) from Int to Int {
	public static inline final None:ImPlotMouseTextFlags = 0;
	public static inline final NoAuxAxes:ImPlotMouseTextFlags = 1;
	public static inline final NoFormat:ImPlotMouseTextFlags = 2;
	public static inline final ShowAlways:ImPlotMouseTextFlags = 4;
}

abstract ImPlotPieChartFlags(Int) from Int to Int {
	public static inline final None:ImPlotPieChartFlags = 0;
	public static inline final Normalize:ImPlotPieChartFlags = 1024;
	public static inline final IgnoreHidden:ImPlotPieChartFlags = 2048;
	public static inline final Exploding:ImPlotPieChartFlags = 4096;
	public static inline final NoSliceBorder:ImPlotPieChartFlags = 8192;
}

abstract ImPlotPolygonFlags(Int) from Int to Int {
	public static inline final None:ImPlotPolygonFlags = 0;
	public static inline final Concave:ImPlotPolygonFlags = 1024;
}

abstract ImPlotProp(Int) from Int to Int {
	public static inline final LineColor:ImPlotProp = 0;
	public static inline final LineColors:ImPlotProp = 1;
	public static inline final LineWeight:ImPlotProp = 2;
	public static inline final FillColor:ImPlotProp = 3;
	public static inline final FillColors:ImPlotProp = 4;
	public static inline final FillAlpha:ImPlotProp = 5;
	public static inline final Marker:ImPlotProp = 6;
	public static inline final MarkerSize:ImPlotProp = 7;
	public static inline final MarkerSizes:ImPlotProp = 8;
	public static inline final MarkerLineColor:ImPlotProp = 9;
	public static inline final MarkerLineColors:ImPlotProp = 10;
	public static inline final MarkerFillColor:ImPlotProp = 11;
	public static inline final MarkerFillColors:ImPlotProp = 12;
	public static inline final Size:ImPlotProp = 13;
	public static inline final Offset:ImPlotProp = 14;
	public static inline final Stride:ImPlotProp = 15;
	public static inline final Flags:ImPlotProp = 16;
}

abstract ImPlotScale(Int) from Int to Int {
	public static inline final Linear:ImPlotScale = 0;
	public static inline final Time:ImPlotScale = 1;
	public static inline final Log10:ImPlotScale = 2;
	public static inline final SymLog:ImPlotScale = 3;
}

abstract ImPlotScatterFlags(Int) from Int to Int {
	public static inline final None:ImPlotScatterFlags = 0;
	public static inline final NoClip:ImPlotScatterFlags = 1024;
}

abstract ImPlotShadedFlags(Int) from Int to Int {
	public static inline final None:ImPlotShadedFlags = 0;
}

abstract ImPlotStairsFlags(Int) from Int to Int {
	public static inline final None:ImPlotStairsFlags = 0;
	public static inline final PreStep:ImPlotStairsFlags = 1024;
	public static inline final Shaded:ImPlotStairsFlags = 2048;
}

abstract ImPlotStemsFlags(Int) from Int to Int {
	public static inline final None:ImPlotStemsFlags = 0;
	public static inline final Horizontal:ImPlotStemsFlags = 1024;
}

abstract ImPlotStyleVar(Int) from Int to Int {
	public static inline final PlotDefaultSize:ImPlotStyleVar = 0;
	public static inline final PlotMinSize:ImPlotStyleVar = 1;
	public static inline final PlotBorderSize:ImPlotStyleVar = 2;
	public static inline final MinorAlpha:ImPlotStyleVar = 3;
	public static inline final MajorTickLen:ImPlotStyleVar = 4;
	public static inline final MinorTickLen:ImPlotStyleVar = 5;
	public static inline final MajorTickSize:ImPlotStyleVar = 6;
	public static inline final MinorTickSize:ImPlotStyleVar = 7;
	public static inline final MajorGridSize:ImPlotStyleVar = 8;
	public static inline final MinorGridSize:ImPlotStyleVar = 9;
	public static inline final PlotPadding:ImPlotStyleVar = 10;
	public static inline final LabelPadding:ImPlotStyleVar = 11;
	public static inline final LegendPadding:ImPlotStyleVar = 12;
	public static inline final LegendInnerPadding:ImPlotStyleVar = 13;
	public static inline final LegendSpacing:ImPlotStyleVar = 14;
	public static inline final MousePosPadding:ImPlotStyleVar = 15;
	public static inline final AnnotationPadding:ImPlotStyleVar = 16;
	public static inline final FitPadding:ImPlotStyleVar = 17;
	public static inline final DigitalPadding:ImPlotStyleVar = 18;
	public static inline final DigitalSpacing:ImPlotStyleVar = 19;
	public static inline final COUNT:ImPlotStyleVar = 20;
}

abstract ImPlotSubplotFlags(Int) from Int to Int {
	public static inline final None:ImPlotSubplotFlags = 0;
	public static inline final NoTitle:ImPlotSubplotFlags = 1;
	public static inline final NoLegend:ImPlotSubplotFlags = 2;
	public static inline final NoMenus:ImPlotSubplotFlags = 4;
	public static inline final NoResize:ImPlotSubplotFlags = 8;
	public static inline final NoAlign:ImPlotSubplotFlags = 16;
	public static inline final ShareItems:ImPlotSubplotFlags = 32;
	public static inline final LinkRows:ImPlotSubplotFlags = 64;
	public static inline final LinkCols:ImPlotSubplotFlags = 128;
	public static inline final LinkAllX:ImPlotSubplotFlags = 256;
	public static inline final LinkAllY:ImPlotSubplotFlags = 512;
	public static inline final ColMajor:ImPlotSubplotFlags = 1024;
}

abstract ImPlotTextFlags(Int) from Int to Int {
	public static inline final None:ImPlotTextFlags = 0;
	public static inline final Vertical:ImPlotTextFlags = 1024;
}

abstract ImPlotTimeFmt(Int) from Int to Int {
	public static inline final None:ImPlotTimeFmt = 0;
	public static inline final Us:ImPlotTimeFmt = 1;
	public static inline final SUs:ImPlotTimeFmt = 2;
	public static inline final SMs:ImPlotTimeFmt = 3;
	public static inline final S:ImPlotTimeFmt = 4;
	public static inline final MinSMs:ImPlotTimeFmt = 5;
	public static inline final HrMinSMs:ImPlotTimeFmt = 6;
	public static inline final HrMinS:ImPlotTimeFmt = 7;
	public static inline final HrMin:ImPlotTimeFmt = 8;
	public static inline final Hr:ImPlotTimeFmt = 9;
}

abstract ImPlotTimeUnit(Int) from Int to Int {
	public static inline final Us:ImPlotTimeUnit = 0;
	public static inline final Ms:ImPlotTimeUnit = 1;
	public static inline final S:ImPlotTimeUnit = 2;
	public static inline final Min:ImPlotTimeUnit = 3;
	public static inline final Hr:ImPlotTimeUnit = 4;
	public static inline final Day:ImPlotTimeUnit = 5;
	public static inline final Mo:ImPlotTimeUnit = 6;
	public static inline final Yr:ImPlotTimeUnit = 7;
	public static inline final COUNT:ImPlotTimeUnit = 8;
}

@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotDateTimeSpec") extern class ImPlotDateTimeSpec extends imguijs.ImGui.ValueStruct {
	@:native("Date")
	var date:Float;
	@:native("Time")
	var time:Float;
	@:native("UseISO8601")
	var useISO8601:Bool;
	@:native("Use24HourClock")
	var use24HourClock:Bool;
	function new(?Date:Float = 0.0, ?Time:Float = 0.0, ?UseISO8601:Bool = false, ?Use24HourClock:Bool = false);
	static function From(obj:ImPlotDateTimeSpec):ImPlotDateTimeSpec;
}

@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotPoint") extern class ImPlotPoint extends imguijs.ImGui.ValueStruct {
	var x:Float;
	var y:Float;
	function new(?x:Float = 0.0, ?y:Float = 0.0);
	static function From(obj:ImPlotPoint):ImPlotPoint;
}

@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotRange") extern class ImPlotRange extends imguijs.ImGui.ValueStruct {
	@:native("Min")
	var min:Float;
	@:native("Max")
	var max:Float;
	function new(?Min:Float = 0.0, ?Max:Float = 0.0);
	static function From(obj:ImPlotRange):ImPlotRange;
}

@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotRect") extern class ImPlotRect extends imguijs.ImGui.ValueStruct {
	@:native("X")
	var x:ImPlotRange;
	@:native("Y")
	var y:ImPlotRange;
	function new(?X:ImPlotRange /* JS default: new ImPlotRange() */, ?Y:ImPlotRange /* JS default: new ImPlotRange() */);
	static function From(obj:ImPlotRect):ImPlotRect;
}

@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotTime") extern class ImPlotTime extends imguijs.ImGui.ValueStruct {
	@:native("S")
	var s:Float;
	@:native("Us")
	var us:Float;
	function new(?S:Float = 0.0, ?Us:Float = 0.0);
	static function From(obj:ImPlotTime):ImPlotTime;
}

@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotSpec") extern class ImPlotSpec extends imguijs.ImGui.ValueStruct {
	@:native("LineColor")
	var lineColor:imguijs.Abstracts.ImVec4;
	@:native("LineWeight")
	var lineWeight:Float;
	@:native("FillColor")
	var fillColor:imguijs.Abstracts.ImVec4;
	@:native("FillAlpha")
	var fillAlpha:Float;
	@:native("Marker")
	var marker:Float;
	@:native("MarkerSize")
	var markerSize:Float;
	@:native("MarkerLineColor")
	var markerLineColor:imguijs.Abstracts.ImVec4;
	@:native("MarkerFillColor")
	var markerFillColor:imguijs.Abstracts.ImVec4;
	@:native("Size")
	var size:Float;
	@:native("Offset")
	var offset:Float;
	@:native("Stride")
	var stride:Float;
	@:native("Flags")
	var flags:Float;
	function new(?LineColor:imguijs.Abstracts.ImVec4 /* JS default: new ImVec4(0.0, 0.0, 0.0, -1.0) */, ?LineWeight:Float = 1.0, ?FillColor:imguijs.Abstracts.ImVec4 /* JS default: new ImVec4(0.0, 0.0, 0.0, -1.0) */, ?FillAlpha:Float = 1.0, ?Marker:Float = 0.0, ?MarkerSize:Float = 4.0, ?MarkerLineColor:imguijs.Abstracts.ImVec4 /* JS default: new ImVec4(0.0, 0.0, 0.0, -1.0) */, ?MarkerFillColor:imguijs.Abstracts.ImVec4 /* JS default: new ImVec4(0.0, 0.0, 0.0, -1.0) */, ?Size:Float = 4.0, ?Offset:Float = 0.0, ?Stride:Float = -1.0, ?Flags:Float = 0.0);
	static function From(obj:ImPlotSpec):ImPlotSpec;
}

@:keep @:native("globalThis.__imguiHxJsImGui.ImPlot") extern class ImPlot {
	static var Auto:Float;
	@:native("AddColormap_U32Ptr")
	static function addColormap_U32Ptr(name:String, cols:Array<Float>, size:Float, ?qual:Bool = true):Float;
	@:native("AddColormap_Vec4Ptr")
	static function addColormap_Vec4Ptr(name:String, cols:Array<imguijs.Abstracts.ImVec4>, size:Float, ?qual:Bool = true):Float;
	@:native("Annotation_Bool")
	static function annotation_Bool(x:Float, y:Float, col:imguijs.Abstracts.ImVec4, pix_offset:imguijs.Abstracts.ImVec2, clamp:Bool, ?round:Bool = false):Void;
	@:native("BeginAlignedPlots")
	static function beginAlignedPlots(group_id:String, ?vertical:Bool = true):Bool;
	@:native("BeginDragDropSourceAxis")
	static function beginDragDropSourceAxis(axis:Float, ?flags:Float = 0.0):Bool;
	@:native("BeginDragDropSourceItem")
	static function beginDragDropSourceItem(label_id:String, ?flags:Float = 0.0):Bool;
	@:native("BeginDragDropSourcePlot")
	static function beginDragDropSourcePlot(?flags:Float = 0.0):Bool;
	@:native("BeginDragDropTargetAxis")
	static function beginDragDropTargetAxis(axis:Float):Bool;
	@:native("BeginDragDropTargetLegend")
	static function beginDragDropTargetLegend():Bool;
	@:native("BeginDragDropTargetPlot")
	static function beginDragDropTargetPlot():Bool;
	@:native("BeginLegendPopup")
	static function beginLegendPopup(label_id:String, ?mouse_button:Float = 1.0):Bool;
	@:native("BeginPlot")
	static function beginPlot(title_id:String, ?size:imguijs.Abstracts.ImVec2 /* JS default: new ImVec2(-1, 0) */, ?flags:Float = 0.0):Bool;
	@:native("BeginSubplots")
	static function beginSubplots(title_id:String, rows:Float, cols:Float, size:imguijs.Abstracts.ImVec2, ?flags:Float = 0.0, ?row_ratios:Array<Float> = null, ?col_ratios:Array<Float> = null):Bool;
	@:native("BustColorCache")
	static function bustColorCache(?plot_title_id:String = ""):Void;
	@:native("CancelPlotSelection")
	static function cancelPlotSelection():Void;
	@:native("ColormapButton")
	static function colormapButton(label:String, ?size:imguijs.Abstracts.ImVec2 /* JS default: new ImVec2(0, 0) */, ?cmap:Float = -1.0):Bool;
	@:native("ColormapIcon")
	static function colormapIcon(cmap:Float):Void;
	@:native("ColormapScale")
	static function colormapScale(label:String, scale_min:Float, scale_max:Float, ?size:imguijs.Abstracts.ImVec2 /* JS default: new ImVec2(0, 0) */, ?format:String = "%g", ?flags:Float = 0.0, ?cmap:Float = -1.0):Void;
	@:native("ColormapSlider")
	static function colormapSlider(label:String, t:Array<Float>, ?out:Array<imguijs.Abstracts.ImVec4> = null, ?format:String = "", ?cmap:Float = -1.0):Bool;
	@:native("CreateContext")
	static function createContext():Float;
	@:native("DestroyContext")
	static function destroyContext(?ctx:Float = 0.0):Void;
	@:native("EndAlignedPlots")
	static function endAlignedPlots():Void;
	@:native("EndDragDropSource")
	static function endDragDropSource():Void;
	@:native("EndDragDropTarget")
	static function endDragDropTarget():Void;
	@:native("EndLegendPopup")
	static function endLegendPopup():Void;
	@:native("EndPlot")
	static function endPlot():Void;
	@:native("EndSubplots")
	static function endSubplots():Void;
	@:native("GetColormapColor")
	static function getColormapColor(idx:Float, ?cmap:Float = -1.0):imguijs.Abstracts.ImVec4;
	@:native("GetColormapCount")
	static function getColormapCount():Float;
	@:native("GetColormapIndex")
	static function getColormapIndex(name:String):Float;
	@:native("GetColormapSize")
	static function getColormapSize(?cmap:Float = -1.0):Float;
	@:native("GetCurrentContext")
	static function getCurrentContext():Float;
	@:native("GetInputMap")
	static function getInputMap():Float;
	@:native("GetLastItemColor")
	static function getLastItemColor():imguijs.Abstracts.ImVec4;
	@:native("GetPlotLimits")
	static function getPlotLimits(?x_axis:Float = -1.0, ?y_axis:Float = -1.0):ImPlotRect;
	@:native("GetPlotMousePos")
	static function getPlotMousePos(?x_axis:Float = -1.0, ?y_axis:Float = -1.0):ImPlotPoint;
	@:native("GetPlotPos")
	static function getPlotPos():imguijs.Abstracts.ImVec2;
	@:native("GetPlotSelection")
	static function getPlotSelection(?x_axis:Float = -1.0, ?y_axis:Float = -1.0):ImPlotRect;
	@:native("GetPlotSize")
	static function getPlotSize():imguijs.Abstracts.ImVec2;
	@:native("GetStyle")
	static function getStyle():Float;
	@:native("HideNextItem")
	static function hideNextItem(?hidden:Bool = true, ?cond:Float = 2.0):Void;
	@:native("IsAxisHovered")
	static function isAxisHovered(axis:Float):Bool;
	@:native("IsLegendEntryHovered")
	static function isLegendEntryHovered(label_id:String):Bool;
	@:native("IsPlotHovered")
	static function isPlotHovered():Bool;
	@:native("IsPlotSelected")
	static function isPlotSelected():Bool;
	@:native("IsSubplotsHovered")
	static function isSubplotsHovered():Bool;
	@:native("ItemIcon_U32")
	static function itemIcon_U32(col:Float):Void;
	@:native("ItemIcon_Vec4")
	static function itemIcon_Vec4(col:imguijs.Abstracts.ImVec4):Void;
	@:native("MapInputDefault")
	static function mapInputDefault(?dst:Float = 0.0):Void;
	@:native("MapInputReverse")
	static function mapInputReverse(?dst:Float = 0.0):Void;
	@:native("NextColormapColor")
	static function nextColormapColor():imguijs.Abstracts.ImVec4;
	@:native("NextMarker")
	static function nextMarker():Float;
	@:native("PixelsToPlot")
	static function pixelsToPlot(x:Float, y:Float, ?x_axis:Float = -1.0, ?y_axis:Float = -1.0):ImPlotPoint;
	@:native("PixelsToPlotVec2")
	static function pixelsToPlotVec2(pix:imguijs.Abstracts.ImVec2, ?x_axis:Float = -1.0, ?y_axis:Float = -1.0):ImPlotPoint;
	@:native("PlotBarGroups")
	static function plotBarGroups(label_ids:Null<Array<String>>, values:Array<Float>, item_count:Float, group_count:Float, ?group_size:Float = 0.67, ?shift:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotBarsXY")
	static function plotBarsXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, bar_size:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotBars")
	static function plotBars(label_id:String, values:Array<Float>, count:Float, ?bar_size:Float = 0.67, ?shift:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotBubblesXY")
	static function plotBubblesXY(label_id:String, xs:Array<Float>, ys:Array<Float>, szs:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotBubbles")
	static function plotBubbles(label_id:String, values:Array<Float>, szs:Array<Float>, count:Float, ?xscale:Float = 1.0, ?xstart:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotDigital")
	static function plotDigital(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotDummy")
	static function plotDummy(label_id:String, ?spec:ImPlotSpec = null):Void;
	@:native("PlotErrorBarsRange")
	static function plotErrorBarsRange(label_id:String, xs:Array<Float>, ys:Array<Float>, neg:Array<Float>, pos:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotErrorBars")
	static function plotErrorBars(label_id:String, xs:Array<Float>, ys:Array<Float>, err:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotHeatmap")
	static function plotHeatmap(label_id:String, values:Array<Float>, rows:Float, cols:Float, ?scale_min:Float = 0.0, ?scale_max:Float = 0.0, ?label_fmt:String = "%.1f", ?bounds_min:ImPlotPoint /* JS default: new ImPlotPoint(0, 0) */, ?bounds_max:ImPlotPoint /* JS default: new ImPlotPoint(1, 1) */, ?spec:ImPlotSpec = null):Void;
	@:native("PlotHistogram")
	static function plotHistogram(label_id:String, values:Array<Float>, count:Float, ?bins:Float = -2.0, ?bar_scale:Float = 1.0, ?range:ImPlotRange /* JS default: new ImPlotRange() */, ?spec:ImPlotSpec = null):Float;
	@:native("PlotHistogram2D")
	static function plotHistogram2D(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?x_bins:Float = -2.0, ?y_bins:Float = -2.0, ?range:ImPlotRect /* JS default: new ImPlotRect() */, ?spec:ImPlotSpec = null):Float;
	@:native("PlotInfLines")
	static function plotInfLines(label_id:String, values:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotLineXY")
	static function plotLineXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotLine")
	static function plotLine(label_id:String, values:Array<Float>, count:Float, ?xscale:Float = 1.0, ?xstart:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotPieChart")
	static function plotPieChart(label_ids:Null<Array<String>>, values:Array<Float>, count:Float, x:Float, y:Float, radius:Float, ?label_fmt:String = "%.1f", ?angle0:Float = 90.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotPolygon")
	static function plotPolygon(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotScatterXY")
	static function plotScatterXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotScatter")
	static function plotScatter(label_id:String, values:Array<Float>, count:Float, ?xscale:Float = 1.0, ?xstart:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotShadedBand")
	static function plotShadedBand(label_id:String, xs:Array<Float>, ys1:Array<Float>, ys2:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotShadedXY")
	static function plotShadedXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?yref:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotShaded")
	static function plotShaded(label_id:String, values:Array<Float>, count:Float, ?yref:Float = 0.0, ?xscale:Float = 1.0, ?xstart:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotStairsXY")
	static function plotStairsXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec = null):Void;
	@:native("PlotStairs")
	static function plotStairs(label_id:String, values:Array<Float>, count:Float, ?xscale:Float = 1.0, ?xstart:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotStemsXY")
	static function plotStemsXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?ref:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotStems")
	static function plotStems(label_id:String, values:Array<Float>, count:Float, ?ref:Float = 0.0, ?scale:Float = 1.0, ?start:Float = 0.0, ?spec:ImPlotSpec = null):Void;
	@:native("PlotText")
	static function plotText(text:String, x:Float, y:Float, ?pix_offset:imguijs.Abstracts.ImVec2 /* JS default: new ImVec2(0, 0) */, ?spec:ImPlotSpec = null):Void;
	@:native("PlotToPixels")
	static function plotToPixels(x:Float, y:Float, ?x_axis:Float = -1.0, ?y_axis:Float = -1.0):imguijs.Abstracts.ImVec2;
	@:native("PlotToPixelsPoint")
	static function plotToPixelsPoint(plt:ImPlotPoint, ?x_axis:Float = -1.0, ?y_axis:Float = -1.0):imguijs.Abstracts.ImVec2;
	@:native("PopColormap")
	static function popColormap(?count:Float = 1.0):Void;
	@:native("PopPlotClipRect")
	static function popPlotClipRect():Void;
	@:native("PopStyleColor")
	static function popStyleColor(?count:Float = 1.0):Void;
	@:native("PopStyleVar")
	static function popStyleVar(?count:Float = 1.0):Void;
	@:native("PushColormap_PlotColormap")
	static function pushColormap_PlotColormap(cmap:Float):Void;
	@:native("PushColormap_Str")
	static function pushColormap_Str(name:String):Void;
	@:native("PushPlotClipRect")
	static function pushPlotClipRect(?expand:Float = 0.0):Void;
	@:native("PushStyleColor_U32")
	static function pushStyleColor_U32(idx:Float, col:Float):Void;
	@:native("PushStyleColor_Vec4")
	static function pushStyleColor_Vec4(idx:Float, col:imguijs.Abstracts.ImVec4):Void;
	@:native("PushStyleVar_Float")
	static function pushStyleVar_Float(idx:Float, val:Float):Void;
	@:native("PushStyleVar_Int")
	static function pushStyleVar_Int(idx:Int, val:Int):Void;
	@:native("PushStyleVar_Vec2")
	static function pushStyleVar_Vec2(idx:Float, val:imguijs.Abstracts.ImVec2):Void;
	@:native("SampleColormap")
	static function sampleColormap(t:Float, ?cmap:Float = -1.0):imguijs.Abstracts.ImVec4;
	@:native("SetAxes")
	static function setAxes(x_axis:Float, y_axis:Float):Void;
	@:native("SetAxis")
	static function setAxis(axis:Float):Void;
	@:native("SetCurrentContext")
	static function setCurrentContext(ctx:Float):Void;
	@:native("SetImGuiContext")
	static function setImGuiContext(ctx:Float):Void;
	@:native("SetNextAxesLimits")
	static function setNextAxesLimits(x_min:Float, x_max:Float, y_min:Float, y_max:Float, ?cond:Float = 2.0):Void;
	@:native("SetNextAxesToFit")
	static function setNextAxesToFit():Void;
	@:native("SetNextAxisLimits")
	static function setNextAxisLimits(axis:Float, v_min:Float, v_max:Float, ?cond:Float = 2.0):Void;
	@:native("SetNextAxisLinks")
	static function setNextAxisLinks(axis:Float, link_min:Array<Float>, link_max:Array<Float>):Void;
	@:native("SetNextAxisToFit")
	static function setNextAxisToFit(axis:Float):Void;
	@:native("SetupAxes")
	static function setupAxes(x_label:String, y_label:String, ?x_flags:Float = 0.0, ?y_flags:Float = 0.0):Void;
	@:native("SetupAxesLimits")
	static function setupAxesLimits(x_min:Float, x_max:Float, y_min:Float, y_max:Float, ?cond:Float = 2.0):Void;
	@:native("SetupAxis")
	static function setupAxis(axis:Float, ?label:String = "", ?flags:Float = 0.0):Void;
	@:native("SetupAxisFormat_Str")
	static function setupAxisFormat_Str(axis:Float, fmt:String):Void;
	@:native("SetupAxisLimits")
	static function setupAxisLimits(axis:Float, v_min:Float, v_max:Float, ?cond:Float = 2.0):Void;
	@:native("SetupAxisLimitsConstraints")
	static function setupAxisLimitsConstraints(axis:Float, v_min:Float, v_max:Float):Void;
	@:native("SetupAxisLinks")
	static function setupAxisLinks(axis:Float, link_min:Array<Float>, link_max:Array<Float>):Void;
	@:native("SetupAxisScale_PlotScale")
	static function setupAxisScale_PlotScale(axis:Float, scale:Float):Void;
	@:native("SetupAxisTicksRange")
	static function setupAxisTicksRange(axis:Float, v_min:Float, v_max:Float, n_ticks:Float, ?labels:Array<String> = null, ?keep_default:Bool = false):Void;
	@:native("SetupAxisTicks")
	static function setupAxisTicks(axis:Float, values:Array<Float>, n_ticks:Float, ?labels:Array<String> = null, ?keep_default:Bool = false):Void;
	@:native("SetupAxisZoomConstraints")
	static function setupAxisZoomConstraints(axis:Float, z_min:Float, z_max:Float):Void;
	@:native("SetupFinish")
	static function setupFinish():Void;
	@:native("SetupLegend")
	static function setupLegend(location:Float, ?flags:Float = 0.0):Void;
	@:native("SetupMouseText")
	static function setupMouseText(location:Float, ?flags:Float = 0.0):Void;
	@:native("ShowColormapSelector")
	static function showColormapSelector(label:String):Bool;
	@:native("ShowInputMapSelector")
	static function showInputMapSelector(label:String):Bool;
	@:native("ShowStyleEditor")
	static function showStyleEditor(?ref:Float = 0.0):Void;
	@:native("ShowStyleSelector")
	static function showStyleSelector(label:String):Bool;
	@:native("ShowUserGuide")
	static function showUserGuide():Void;
	@:native("StyleColorsAuto")
	static function styleColorsAuto(?dst:Float = 0.0):Void;
	@:native("StyleColorsClassic")
	static function styleColorsClassic(?dst:Float = 0.0):Void;
	@:native("StyleColorsDark")
	static function styleColorsDark(?dst:Float = 0.0):Void;
	@:native("StyleColorsLight")
	static function styleColorsLight(?dst:Float = 0.0):Void;
	@:native("TagX_Bool")
	static function tagX_Bool(x:Float, col:imguijs.Abstracts.ImVec4, ?round:Bool = false):Void;
	@:native("TagY_Bool")
	static function tagY_Bool(y:Float, col:imguijs.Abstracts.ImVec4, ?round:Bool = false):Void;
	@:native("InputMap_destroy")
	static function inputMap_destroy(self:Float):Void;
	@:native("InputMap_ImPlotInputMap")
	static function inputMap_ImPlotInputMap():Float;
	@:native("Style_destroy")
	static function style_destroy(self:Float):Void;
	@:native("Style_ImPlotStyle")
	static function style_ImPlotStyle():Float;
}
